### ISSUE TITLE
I get only black in OBS

### ISSUE THREAD

**Issue by newemka** [Off-World-Live/obs-spout2-source-plugin#12]
Hello
I've tried the two latest releases and i only get black when i add Spout 2 OBS source.
OBS detects the right size of the spout source. The size is updated when i select other spout senders.

I'm using Spout 2.006 and OBS 26.0.2 (64bit)

I will try Spout 2.006 Update 4 and see if it fix the issue.

I'm on Win 10 version: 1909
Computer is laptop Gigabyte aero 15 with GTX1060 GPU
I've tested with the latest Nvidia drivers and 442.53

System capabilities displayed by Spout DX11 Sender :
Spout Sender (Vers 2.018)
DirectX 9.0c available
NVIDIA GeForce GTX 1060 (Display)
Microsoft Basic Render Driver (Secondary)
Current adapter : NVIDIA Corporation
NV_DX_interop extension available
DirectX 11 Texture share mode

System capabilities displayed by Spout DX11 Receiver :
Spout Receiver - DirectX 11 (Vers 2.020)
DirectX 9.0c available
NVIDIA GeForce GTX 1060 (Display)
Microsoft Basic Render Driver (Secondary)
Current adapter : NVIDIA Corporation
NV_DX_interop extension available
DirectX 11 Texture share mode

System capabilities displayed by ShaderToySender:
Spout Sender - DirectX 11
DirectX 9.0c available
NVIDIA GeForce GTX 1060 (Display)
Microsoft Basic Render Driver (Secondary)
NV_DX_interop extensions supported
Texture share mode

I hope I gave enough details. 

Cheers!

**Comment by campbellwmorgan** [comment]
Hi!

Thanks for the bug report. So I think this is almost certainly a GPU issue. If you click on a program shortcut on your computer is there an option "run with..." and an option like "Intel" and then "Nvidia GTX 1060"?

In the past, people that have had this black screen have had it because they are sending to spout using one GPU and trying to receive using another. So ideally, you want both programs using the same GPU.

Firstly, ensure that you are running "ShaderToySender" with "Run on Nvidia ...". If it is still black, try following these instructions https://obsproject.com/wiki/Laptop-Troubleshooting to ensure that OBS itself is running with the correct GPU.

If that doesn't help, leave a message here and we'll investigate if it has something to do with the OBS plugin instead.

**Comment by newemka** [comment]
Hi! 
Thanks for the answer. In fact I don't get black, the spout frame is transparent in OBS. I've checked about the GPU and I'm using the Nvidia GTX 1060 with OBS and all senders.

**Comment by campbellwmorgan** [comment]
Ok thanks for trying that. Spout can send a lot of formats, but the OBS plugin can only receive 8bit textures. Could you try downloading https://leadedge.github.io/spout-download.html and running the "Spout Sender" which is in the folder `SPOUT-2006_UPDATE-4\DEMO\x64` ensuring that you right click and run it with the nvidia GPU. If that works, then it is indeed that your shader toy sender is sending the texture in a funky format.

**Comment by newemka** [comment]
You can close the issue :)

**Comment by campbellwmorgan** [comment]
Glad to hear you sorted it!

**Comment by newemka** [comment]
Thank you so much for this plugin :)
