### ISSUE TITLE
Installs fine but doesn't show on obs preview

### ISSUE THREAD

**Issue by capellavacancies** [Off-World-Live/obs-spout2-source-plugin#13]
Installed with no issue, and it's possible to add it as source but the preview doesn't show anything.
I can choose between different spout options, like hd preview, sender etc but still nothing appears on obs canvas
I see the resolution changing if I change my spout output settings, some something is coming through but doesn't get displayed.

using 26.0.2
on windows 10
Any idea ?
thanks

**Comment by shugen002** [comment]
Do you have multi GPU ? Please make sure OBS and your source run on same GPU.

**Comment by capellavacancies** [comment]
> 
> 
> Do you have multi GPU ? Please make sure OBS and your source run on same GPU.

thanks mate, I just come here to write that it's probably related to this
https://obsproject.com/wiki/Laptop-GPU-Selection-Windows-10
I'll check when home and update
thanks for the reply though

**Comment by capellavacancies** [comment]
Thanks for the support, it was something with my graphics adapter. I enabled all files reposnible both for spout and for obs to be ran with the nvidia card and now works flawlessly.
Have a nice a weekend

**Comment by Inui-senpai** [comment]
I had the same issue with VTube Studio and Streamlabs OBS, and I managed to fix it. If you use the latter, just add `obs64.exe` (located in `(SLOBS install directory)\resources\app.asar.unpacked\node_modules\obs-studio-node`) in the System - Display - Graphics page in the Settings and set _High performance_ mode instead of _Let Windows decide_.
