### ISSUE TITLE
alpha channel black?

### ISSUE THREAD

**Issue by phields** [Off-World-Live/obs-spout2-source-plugin#4]
is there any alpha channel support?

**Comment by campbellwmorgan** [comment]
I hadn't tested it with alpha channels, but the incoming texture is RGBA so it might be possible.

I suspect the problem is https://github.com/Off-World-Live/obs-spout2-source-plugin/blob/master/win-spout.cpp#L328 and it may just work by replacing with the the enum `OBS_EFFECT_PREMULTIPLIED_ALPHA` although we would probably also have to premultiply the texture.

Unless anybody wants to have a go and submit a PR, i'll have a crack at it if I have time
